### ISSUE TITLE
Support for Aurora PostgreSQL

### ISSUE THREAD

**Issue by eduardopuente** [Rungutan/sentry-fargate-cf-stack#23] opened 2021-01-27 09:53 UTC
Would be possible to offer support for Aurora?
Or is there any compatibility issue?

**Comment by nodomain** [comment] 2021-01-27 09:57
See our discussion in #16

**Comment by mariusmitrofan** [comment] 2021-01-29 07:43
Closing issue as duplicate of https://github.com/Rungutan/sentry-fargate-cf-stack/issues/16

**Closed as completed by mariusmitrofan** 2021-01-29 07:43 UTC
